// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://avguxrfduehvysdnegqv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2Z3V4cmZkdWVodnlzZG5lZ3F2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE3NzkzMTksImV4cCI6MjA4NzM1NTMxOX0.d1VKS6Wnr-jTASKCjDMwLBJJwLZO-_rOow6Rm0rLa24";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});